language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - cp config.tests.php config.php
  - bin/setup codeup:db:create
  - bin/setup migrations:migrate
  - npm install -g phantomjs-prebuilt

script:
  - bin/phpspec run -v
  - bin/phpunit -v
