language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - npm install -g phantomjs-prebuilt
  - cd applications/console && composer install --prefer-source --no-interaction
  - bin/setup codeup:db:create
  - bin/setup migrations:migrate -n

script:
  - bin/phpunit -v
  - cd ../../packages/attendance
  - bin/phpspec run -v
