language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - bin/setup codeup:db:create
  - bin/setup migrations:migrate

script:
  - bin/phpspec run -v
  - bin/phpunit -v
