console:
  build: .
  links:
    - db
  volumes:
    - ./../../:/usr/src/myapp
data:
  build: ./../../containers/data
db:
  image: "mysql:5.7"
  volumes_from:
    - data
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: dev_password
    MYSQL_USER: dev_attendance_user
    MYSQL_PASSWORD: dev_attendance_password
    MYSQL_DATABASE: attendance_db
